name: Check Formatting

on:
  pull_request:
  push:
    branches: [main]

permissions: {}

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "npm"

      # Or yarn, npm, etc.
      - run: npm install --frozen-lockfile
      - run: npm run fmt:check
