name: Check Formatting

on:
  pull_request:
  push:
    branches: [main]

permissions: {}

jobs:
  format-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Check frontend formatting
        working-directory: ./frontend
        run: npm run fmt:check

  format-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Check backend formatting
        working-directory: ./backend
        run: npm run fmt:check
