name: Build and Zip Extension

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-frontend:
    name: Build Frontend Extension
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Upload extension artifacts
        uses: actions/upload-artifact@v6
        with:
          name: firefox-web-extension
          path: frontend/release

  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: ./backend
        run: npm ci

      - name: Build backend
        working-directory: ./backend
        run: npm run build

      - name: Upload backend artifacts
        uses: actions/upload-artifact@v6
        with:
          name: backend-dist
          path: backend/dist
