name: Build and Zip Extension

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Upload extension artifacts
        uses: actions/upload-artifact@v6
        with:
          name: firefox-web-extension
          path: release
